// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeNNZsxeGs7Iyd9FmHe26DLB-Om3Ocmvg',
    appId: '1:538909784173:web:36a84bdd601e3c27d3e764',
    messagingSenderId: '538909784173',
    projectId: 'scholarai-1f4ae',
    authDomain: 'scholarai-1f4ae.firebaseapp.com',
    storageBucket: 'scholarai-1f4ae.firebasestorage.app',
    measurementId: 'G-X830721N1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4hC1cYC4-vnexIKZR5vvIPJ15gf-dstI',
    appId: '1:538909784173:android:1d4e76c4fa354932d3e764',
    messagingSenderId: '538909784173',
    projectId: 'scholarai-1f4ae',
    storageBucket: 'scholarai-1f4ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXsrDVL1a6ljdIOaDW_MGvIDdmP06Zb8',
    appId: '1:538909784173:ios:4c48cb5247595384d3e764',
    messagingSenderId: '538909784173',
    projectId: 'scholarai-1f4ae',
    storageBucket: 'scholarai-1f4ae.firebasestorage.app',
    androidClientId: '538909784173-7l5lfudo94tfefkk4ncscrgo1dttm773.apps.googleusercontent.com',
    iosClientId: '538909784173-3emrpjm84felvmauf0s5bqj64m954021.apps.googleusercontent.com',
    iosBundleId: 'edu.dku.scholarai.scholarai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqXsrDVL1a6ljdIOaDW_MGvIDdmP06Zb8',
    appId: '1:538909784173:ios:4c48cb5247595384d3e764',
    messagingSenderId: '538909784173',
    projectId: 'scholarai-1f4ae',
    storageBucket: 'scholarai-1f4ae.firebasestorage.app',
    androidClientId: '538909784173-7l5lfudo94tfefkk4ncscrgo1dttm773.apps.googleusercontent.com',
    iosClientId: '538909784173-3emrpjm84felvmauf0s5bqj64m954021.apps.googleusercontent.com',
    iosBundleId: 'edu.dku.scholarai.scholarai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeNNZsxeGs7Iyd9FmHe26DLB-Om3Ocmvg',
    appId: '1:538909784173:web:f9ab9e53aac34916d3e764',
    messagingSenderId: '538909784173',
    projectId: 'scholarai-1f4ae',
    authDomain: 'scholarai-1f4ae.firebaseapp.com',
    storageBucket: 'scholarai-1f4ae.firebasestorage.app',
    measurementId: 'G-GN1PNY26C8',
  );
}
